# Generated by Django 3.0.5 on 2020-04-25 17:48

import ClgAdmin.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_activity',
            fields=[
                ('admin_ac_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('course', models.CharField(choices=[('select', 'Select Course'), ('bca', 'BCA'), ('b.com', 'B.com'), ('bba', 'BBA')], default='Select Course', max_length=10)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_extend',
            fields=[
                ('admin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('clg_name', models.CharField(max_length=255)),
                ('admin_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_activity',
            fields=[
                ('fac_ac_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(default=None, max_length=40)),
                ('admin_ac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.Admin_activity')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sem_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TempFileField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_file', models.FileField(blank=True, default=None, upload_to='College/Faculty')),
                ('stud_file', models.FileField(default=None, upload_to='College/Student')),
            ],
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('vid_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vid_text', models.CharField(max_length=255, null=True)),
                ('vid_dur', models.CharField(default=None, max_length=10, null=True)),
                ('vid_up_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vid_path', models.ImageField(upload_to='Videos')),
                ('fac_ac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.Faculty_activity')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('stud_id', models.CharField(blank=True, max_length=10)),
                ('stud_gmail', models.EmailField(max_length=127, unique=True)),
                ('stud_firstname', models.CharField(max_length=50)),
                ('stud_lastname', models.CharField(max_length=50)),
                ('stud_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_ac_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.Admin_activity')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', ClgAdmin.models.MyStudentManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student_activity',
            fields=[
                ('stud_ac_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('view_st', models.BooleanField(default=False)),
                ('view_time', models.TimeField()),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.StudentModel')),
                ('vid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.VideoUpload')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fac_gmail', models.EmailField(max_length=127, unique=True)),
                ('fac_firstname', models.CharField(max_length=50)),
                ('fac_lastname', models.CharField(max_length=50)),
                ('fac_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', ClgAdmin.models.MyFaculyManager()),
            ],
        ),
        migrations.AddField(
            model_name='faculty_activity',
            name='fac_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.FacultyModel'),
        ),
        migrations.CreateModel(
            name='Fac_notes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('note_text', models.CharField(max_length=255, null=True)),
                ('note_file_path', models.ImageField(upload_to='Notes')),
                ('note_up_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fac_ac_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.Faculty_activity')),
            ],
        ),
        migrations.AddField(
            model_name='admin_activity',
            name='sem_id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.Semester'),
        ),
    ]
