# Generated by Django 3.0.5 on 2020-04-27 05:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ClgAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_activity',
            fields=[
                ('assign_ac_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('assign_ac_text', models.CharField(max_length=255, null=True)),
                ('assign_file_path', models.ImageField(upload_to='Notes')),
                ('assign_up_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fac_ac_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.Faculty_activity')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('assign_text', models.CharField(max_length=255, null=True)),
                ('assign_file_path', models.ImageField(upload_to='Notes')),
                ('assign_up_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assign_ac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.Assignment_activity')),
                ('fac_ac_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.Faculty_activity')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.Student_activity')),
            ],
        ),
    ]
