# Generated by Django 3.0.5 on 2020-04-28 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ClgAdmin', '0002_assignment_assignment_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_submit',
            fields=[
                ('assign_submit_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('assign_text', models.CharField(max_length=255, null=True)),
                ('assign_file_path', models.ImageField(upload_to='Notes')),
                ('assign_up_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assign_ac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.Assignment_activity')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClgAdmin.StudentModel')),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
